version: "3.8"
volumes:
  db-store:
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "sudo ./setup.sh && tail -f /dev/null"
    tty: true
    stdin_open: true
    privileged: true
    volumes:
      - ./:/workspace
    networks:
      - dev-app-net

networks:
  dev-app-net:
    driver: bridge